/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ojdbcexercise.views;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ojdbcexercise.controllers.RelationController1;

/**
 *
 * @author Laila
 */
public class Panel2_Admin extends javax.swing.JPanel {
private RelationController1 countryController;
GridBagLayout layout= new GridBagLayout();
LoginPanel lp;
RegisterViewPanel registerPanel2;
TransBevPanel countryPanel1_1;
ForgotPassPanel forgotPassPanel;

    /**
     * Creates new form CountryPanel2
     */
    public Panel2_Admin() {
        initComponents();
        this.countryController = new RelationController1();
        lp = new LoginPanel();
        registerPanel2= new RegisterViewPanel();
        countryPanel1_1= new TransBevPanel();
        forgotPassPanel= new ForgotPassPanel();
        pn1.setLayout(layout);
        GridBagConstraints bagConstraints = new GridBagConstraints();
        bagConstraints.gridx=0;
        bagConstraints.gridy=0;
        pn1.add(lp,bagConstraints);
        pn1.add(registerPanel2,bagConstraints);
        pn1.add(countryPanel1_1,bagConstraints);
        pn1.add(forgotPassPanel, bagConstraints);
//        pn1.add(transactionPanel1,bagConstraints);
        bagConstraints.gridx=0;
        bagConstraints.gridy=0;
        lp.setVisible(false);
        registerPanel2.setVisible(false);
        countryPanel1_1.setVisible(true);
        forgotPassPanel.setVisible(false);
        pnReport.setBackground(Color.white);
        pnLogout.setBackground(Color.pink);
        pnRegis.setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dpMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnReport = new javax.swing.JPanel();
        lbCountry = new javax.swing.JLabel();
        pnRegis = new javax.swing.JPanel();
        lbRegister = new javax.swing.JLabel();
        pnLogout = new javax.swing.JPanel();
        lbLogout = new javax.swing.JLabel();
        pn1 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 204, 255));
        setForeground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dpMain.setBackground(new java.awt.Color(255, 153, 153));
        dpMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("WELCOME ,");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 60));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("ADMIN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-home-address-64.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 70));

        dpMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 105));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnReport.setBackground(new java.awt.Color(255, 204, 255));
        pnReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCountry.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCountry.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-coffee-24.png")); // NOI18N
        lbCountry.setText("Report Sales");
        lbCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCountryMouseReleased(evt);
            }
        });
        pnReport.add(lbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jPanel1.add(pnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        pnRegis.setBackground(new java.awt.Color(255, 204, 255));
        pnRegis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegister.setBackground(new java.awt.Color(255, 204, 255));
        lbRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRegister.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-login-rounded-up-24.png")); // NOI18N
        lbRegister.setText("Register");
        lbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbRegisterMouseReleased(evt);
            }
        });
        pnRegis.add(lbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(pnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 50));

        pnLogout.setBackground(new java.awt.Color(255, 204, 255));
        pnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogout.setBackground(new java.awt.Color(255, 204, 255));
        lbLogout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLogout.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-export-26.png")); // NOI18N
        lbLogout.setText("Logout");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbLogoutMouseReleased(evt);
            }
        });
        pnLogout.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jPanel1.add(pnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 50));

        dpMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 500));

        pn1.setBackground(new java.awt.Color(255, 153, 153));
        pn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dpMain.add(pn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 830, 600));

        add(dpMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void lbLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseReleased
       jPanel1.setVisible(false);
       jPanel2.setVisible(false);
        countryPanel1_1.setVisible(false);
        pnLogout.setBackground(Color.white);
        lp.setVisible(true);
    }//GEN-LAST:event_lbLogoutMouseReleased

    private void lbCountryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCountryMouseReleased

forgotPassPanel.setVisible(false);
        lp.setVisible(false);
        countryPanel1_1.setVisible(true);
        registerPanel2.setVisible(false);
        pnReport.setBackground(Color.white);
        pnLogout.setBackground(Color.pink);
        pnRegis.setBackground(Color.pink);
    }//GEN-LAST:event_lbCountryMouseReleased

    private void lbRegisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseReleased
        forgotPassPanel.setVisible(false);
        lp.setVisible(false);
        countryPanel1_1.setVisible(false);
        registerPanel2.setVisible(true);
        pnReport.setBackground(Color.pink);
        pnLogout.setBackground(Color.pink);
        pnRegis.setBackground(Color.white);

    }//GEN-LAST:event_lbRegisterMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dpMain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pnLogout;
    private javax.swing.JPanel pnRegis;
    private javax.swing.JPanel pnReport;
    // End of variables declaration//GEN-END:variables

}
