/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ojdbcexercise.views;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import ojdbcexercise.controllers.TransactionController1;
import ojdbcexercise.models.Beverages;
import ojdbcexercise.models.Transactionbeverage;
import oracle.jdbc.pool.OracleDataSource;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Laila
 */
public class TransBevPanel extends javax.swing.JPanel {

    private TransactionController1 transactionController;
    GridBagLayout layout = new GridBagLayout();
    DefaultTableModel tableModel = null;
    Connection connection = null;

    /**
     * Creates new form TransBevPanel
     */
    public TransBevPanel() {
        initComponents();
        this.transactionController = new TransactionController1();
        loadData(transactionController.getDataTransaction());
        FillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCountry = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbNameBev = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdTrans = new javax.swing.JTextField();
        btnAddTrans = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("REPORT SALES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 40));

        tblCountry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCountryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCountry);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 460, 150));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-google-web-search-24.png")); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 20, 20));

        btnExcel.setBackground(new java.awt.Color(255, 153, 153));
        btnExcel.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-xls-24.png")); // NOI18N
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 20, 30));

        btnPdf.setBackground(new java.awt.Color(255, 153, 153));
        btnPdf.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-pdf-24.png")); // NOI18N
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });
        jPanel2.add(btnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 20, 30));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("Quantity");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setText("Description");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jPanel4.add(cbNameBev, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel4.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 57, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, 78));

        btnEdit.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-edit-image-24.png")); // NOI18N
        btnEdit.setToolTipText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 26, 28));

        btnDelete.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-delete-bin-24.png")); // NOI18N
        btnDelete.setToolTipText("Delete transaction");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 24, 28));

        btnSave.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-save-24.png")); // NOI18N
        btnSave.setToolTipText("Insert Transaction each Beverage");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 26, 28));

        jLabel5.setText("Transaction Id");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtIdTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTransActionPerformed(evt);
            }
        });
        jPanel4.add(txtIdTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 57, -1));

        btnAddTrans.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\bootcamp\\Other\\Images\\icons8-add-new-24.png")); // NOI18N
        btnAddTrans.setToolTipText("add new transaction");
        btnAddTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTransActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 26, 28));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 309, 460, 230));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 558));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCountryMouseClicked
        int row = tblCountry.getSelectedRow();
        String transbevid = tblCountry.getValueAt(row, 1).toString();
        String bevid = transbevid.substring(4);
        String transid = transbevid.substring(0, 4);
        Transactionbeverage transbev = new TransactionController1().getByIdTransBevController(transid, bevid);

        String quantity = transbev.getQuantity().toString();
        String desc = transbev.getDescription();
        txtDesc.setText(desc);
        txtQuantity.setText(quantity);
        txtIdTrans.setText(transid);

    }//GEN-LAST:event_tblCountryMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String keyword = "%" + txtSearch.getText() + "%";
            clearSearchField();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = "%" + txtSearch.getText() + "%";
        //        loadData(relationController.findCountry(keyword));
        clearSearchField();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed

        XSSFWorkbook excelJTabelExporter = null;
        BufferedOutputStream excelBOU = null;
        FileOutputStream excelFOU = null;

        JFileChooser excelFileChooser = new JFileChooser("D:\\Git\\Export");
        excelFileChooser.setDialogTitle("Save as");

        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "x;xs");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelJTabelExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTabelExporter.createSheet("Sheet 1");
                for (int i = 0; i <= tableModel.getRowCount(); i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < tableModel.getColumnCount(); j++) {
                        XSSFCell excelCell = excelRow.createCell(j);
                        if (i == 0) {
                            excelCell.setCellValue(tableModel.getColumnName(j));
                        } else {
                            excelCell.setCellValue(tableModel.getValueAt(i - 1, j).toString());

                        }

                    }

                }
                excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTabelExporter.write(excelBOU);
                JOptionPane.showMessageDialog(this, "Exported Excel Sucessfully!");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }
                    if (excelJTabelExporter != null) {
                        excelJTabelExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        JFileChooser pdfFileChooser = new JFileChooser("D:\\Git\\Export");
        pdfFileChooser.setDialogTitle("Save as");
        int pdfChooser = pdfFileChooser.showSaveDialog(null);

        if (pdfChooser == JFileChooser.APPROVE_OPTION) {

        }
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(pdfFileChooser.getSelectedFile() + ".pdf"));
            doc.open();

            PdfPTable pdf = new PdfPTable(tableModel.getColumnCount());

            for (int i = 0; i <= tableModel.getRowCount(); i++) {
                for (int j = 0; j < tableModel.getColumnCount(); j++) {
                    if (i == 0) {
                        pdf.addCell(tableModel.getColumnName(j));
                    } else {
                        pdf.addCell(tableModel.getValueAt(i - 1, j).toString());
                    }
                }
            }
            doc.add(pdf);
            JOptionPane.showMessageDialog(this, "Exported Pdf Sucessfully!");
        } catch (FileNotFoundException ex) {
        } catch (DocumentException ex) {
        }
        doc.close();
    }//GEN-LAST:event_btnPdfActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure to save this data?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        String transaction = txtIdTrans.getText();
        String namebev = cbNameBev.getSelectedItem().toString();
        Beverages b1 = new TransactionController1().getIdByNameBevController(namebev);
        String bev = b1.getId();
        String quantity = txtQuantity.getText();
        String desc = txtDesc.getText();
        String msg = "cancelled";
        if (confirm == 0) {
            msg = this.transactionController.updateTransbevController(transaction, bev, quantity, desc);
            JOptionPane.showMessageDialog(this, msg);
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, msg);
        }

        loadData(transactionController.getDataTransaction());
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure to save this data?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
            String beverage = cbNameBev.getSelectedItem().toString();
            String quantity = txtQuantity.getText();
            String desc = txtDesc.getText();
            Beverages b1 = new TransactionController1().getIdByNameBevController(beverage);
            String bev = b1.getId();
            String msg = "cancelled";

            if (confirm == 0) {
                msg = this.transactionController.insertTransBev(bev, quantity, desc);
                JOptionPane.showMessageDialog(this, msg);
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, msg);
            }

            loadData(transactionController.getDataTransaction());
        } catch (ParseException ex) {
            Logger.getLogger(TransBevPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTransActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure to delete this data?", "WARNING", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        String bevname = cbNameBev.getSelectedItem().toString();
        Beverages b1 = new TransactionController1().getIdByNameBevController(bevname);
        String bev = b1.getId();
        String trans = txtIdTrans.getText();

        String msg = "Cancelled";
        if (confirm == 0) {

            msg = this.transactionController.deleteTransBevController(bev, trans);
        }

        JOptionPane.showMessageDialog(this, msg, "WARNING", JOptionPane.ERROR_MESSAGE);
        loadData(transactionController.getDataTransaction());
        clearFields();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTransActionPerformed
        try {
            transactionController.insertTrans("62");
        } catch (ParseException ex) {
            Logger.getLogger(TransBevPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddTransActionPerformed
    private static JDialog createDialog(final JFrame frame) {
        final JDialog modelDialog = new JDialog(frame, "Swing Tester",
                Dialog.ModalityType.DOCUMENT_MODAL);
        modelDialog.setBounds(132, 132, 300, 200);
        Container dialogContainer = modelDialog.getContentPane();
        dialogContainer.setLayout(new BorderLayout());
        dialogContainer.add(new JLabel("                         Welcome to Swing!"),
                 BorderLayout.CENTER);
        JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout());
        JButton okButton = new JButton("Ok");
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                modelDialog.setVisible(false);
            }
        });

        panel1.add(okButton);
        dialogContainer.add(panel1, BorderLayout.SOUTH);

        return modelDialog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrans;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbNameBev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCountry;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtIdTrans;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
   private void FillCombo() {
        try {
            OracleDataSource dataSource = new OracleDataSource();
            dataSource.setDriverType("thin");
            dataSource.setServerName("localhost");
            dataSource.setPortNumber(1521);
            dataSource.setUser("SYSTEM");
            dataSource.setPassword("b0o7c@mp");
            dataSource.setServiceName("XE");

            connection = dataSource.getConnection();
            connection.createStatement().execute("alter session SET current_schema =HR");
            Statement statement = connection.createStatement();
            String query = "select name from beverages";
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                cbNameBev.addItem(resultSet.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TransBevPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void clearFields() {

    }

    /**
     * This method for clearing input in txtSearch field , when button search
     * clicked
     */
    private void clearSearchField() {
        txtSearch.setText(null);

    }

    private void loadData(List<Transactionbeverage> transbevs) {
        String header[] = {"No", "ID", "Jumlah"};
        String[][] data = new String[transbevs.size()][3];

        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1) + "";
            String namebev = transbevs.get(i).getBeverages().getName() + "";
            Beverages b1 = new TransactionController1().getIdByNameBevController(namebev);
            String bev = b1.getId();
            data[i][1] = transbevs.get(i).getTransaction1().getId() + "" + bev;
            data[i][2] = (transbevs.get(i).getBeverages().getPrice()) * (transbevs.get(i).getQuantity()) + "";

        }
        tableModel = new DefaultTableModel(data, header);
        tblCountry.setModel(tableModel);

    }
}
